### ISSUE TITLE
Cannot analyse solution

### ISSUE THREAD

**Issue by smeulend** [eNeRGy164/LivingDocumentation#37]
I Guess that this needs to be more robust. Rather skip something than not doing anything

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at LivingDocumentation.Program.<>c.<AnalyzeSolutionAsync>b__8_3(IPackageReference pr) in /home/vsts/work/1/s/src/LivingDocumentation.Analyzer/Program.cs:line 63
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at LivingDocumentation.Program.<>c__DisplayClass8_0.<AnalyzeSolutionAsync>b__1(Project p) in /home/vsts/work/1/s/src/LivingDocumentation.Analyzer/Program.cs:line 63
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at LivingDocumentation.Program.AnalyzeSolutionAsync(IList`1 types, String solutionFile) in /home/vsts/work/1/s/src/LivingDocumentation.Analyzer/Program.cs:line 65
   at LivingDocumentation.Program.RunApplicationAsync(Options options) in /home/vsts/work/1/s/src/LivingDocumentation.Analyzer/Program.cs:line 38
   at LivingDocumentation.Program.Main(String[] args) in /home/vsts/work/1/s/src/LivingDocumentation.Analyzer/Program.cs:line 25
   at LivingDocumentation.Program.<Main>(String[] args)

**Comment by smeulend** [comment]
It seems that the PackageReference Name can be null

**Comment by eNeRGy164** [comment]
Do you have a sample to recreate this?

**Comment by eNeRGy164** [comment]
In your project, it fails because of this construct:

```
<ItemGroup>
    <PackageReference Update="Microsoft.NETCore.App" Version="2.1.0" />
</ItemGroup>
```

This is not picked up by Buildalyzer. It expects only `Include` as a property to get the name.
