### ISSUE TITLE
Unhandled exception thrown if property has type of `ref T`

### ISSUE THREAD

**Issue by Akarinnnnn** [eNeRGy164/LivingDocumentation#70]
I made a specialized collection for mutable large structs. To mutate a struct member by this indexer, it returns a reference. While analyzer processing this file, it thrown an exception and stopped generation.

Here is the repro code snippet:
```csharp
	public struct ListStruct<T> : IEnumerable<T> where T : unmanaged
	{
		internal int CountInternal;
		private T[] _storage;

		// ...

		public readonly ref T this[int index]
		{
			[method: MethodImpl(MethodImplOptions.AggressiveInlining)]
			get => ref _storage[index];
		}

		// ...
```

And here is the stack trace:
> System.Collections.Generic.KeyNotFoundException: Could not resolve a display name for ref T
>    at LivingDocumentation.SemanticModelExtensions.GetTypeDisplayString(SemanticModel semanticModel, ExpressionSyntax expression) in /\_/src/LivingDocumentation.Analyzer/Extensions/SemanticModelExtensions.cs:line 24
>    at LivingDocumentation.SourceAnalyzer.VisitPropertyDeclaration(PropertyDeclarationSyntax node) in /\_/src/LivingDocumentation.Analyzer/Analyzers/SourceAnalyzer.cs:line 158
>    at Microsoft.CodeAnalysis.CSharp.Syntax.PropertyDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
> ...

Hope these information will help.

**Comment by eNeRGy164** [comment]
Hi, thanks for reporting the issue, at the moment I can't reproduce this. My test code:

```csharp
using System.Collections;
using System.Runtime.CompilerServices;

internal class Program
{
    private static void Main(string[] args)
    {
        Console.WriteLine("Hello, World!");

        var list = new ListStruct<int>();
        var value = list[0];
    }
}

public struct ListStruct<T> : IEnumerable<T> where T : unmanaged
{
    internal int CountInternal;
    private T[] _storage;

    // ...

    public readonly ref T this[int index]
    {
        [method: MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => ref _storage[index];
    }

    public IEnumerator<T> GetEnumerator()
    {
        throw new NotImplementedException();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        throw new NotImplementedException();
    }
}
```

I guess some additional code is required to trigger the issue.

My sample code is dotnet 8.0, I tested with the analyzer from 6.0, 7.0 and 8.0. But none failed.

**Comment by Akarinnnnn** [comment]
Hi, thank you for your reply. When this exception thrown, I'm using PlantUML generator. Is this issue is PUML specific?

**Comment by eNeRGy164** [comment]
Your stack trace mentions code in the analyzer, so I don't think the PlantUML generation has a role.

Is it possible to share a minimal solution so it can be reproduced?

**Comment by Akarinnnnn** [comment]
Sure.
- Command line 
- `livingdoc-analyze --project .\ld-analyzer-ref-t.csproj --solution .\ld-analyzer-ref-t.csproj --output bin\lda\`
- Version
- 0.5.0+Branch.main.Sha.cb303574b42fd324ac3074635613b55f5adb28ee.cb303574b42fd324ac3074635613b55f5adb28ee

Repro project here:
[ld-analyzer-ref-t-repro.zip](https://github.com/eNeRGy164/LivingDocumentation/files/14994371/ld-analyzer-ref-t-repro.zip)

**Comment by Akarinnnnn** [comment]
dotnet info output

> .NET SDK:
> 
> .NET SDK:
>  Version:           8.0.204
>  Commit:            c338c7548c
>  Workload version:  8.0.200-manifests.7d36c14f
> 
> 运行时环境:
>  OS Name:     Windows
>  OS Version:  10.0.22631
>  OS Platform: Windows
>  RID:         win-x64
>  Base Path:   C:\Program Files\dotnet\sdk\8.0.204\
> 
> 已安装 .NET 工作负载:
> 没有要显示的已安装工作负载。
> 
> Host:
>   Version:      8.0.4
>   Architecture: x64
>   Commit:       2d7eea2529
> 
> .NET SDKs installed:
>   6.0.301 [C:\Program Files\dotnet\sdk]
>   6.0.321 [C:\Program Files\dotnet\sdk]
>   8.0.202 [C:\Program Files\dotnet\sdk]
>   8.0.204 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> Other architectures found:
>   x86   [C:\Program Files (x86)\dotnet]
>     registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
> 
> Environment variables:
>   Not set
> 
> global.json file:
>   Not found
> 
> Learn more:
>   https://aka.ms/dotnet/info
> 
> Download .NET:
>   https://aka.ms/dotnet/download
>  Version:           8.0.204
>  Commit:            c338c7548c
>  Workload version:  8.0.200-manifests.7d36c14f
> 
> 运行时环境:
>  OS Name:     Windows
>  OS Version:  10.0.22631
>  OS Platform: Windows
>  RID:         win-x64
>  Base Path:   C:\Program Files\dotnet\sdk\8.0.204\
> 
> 已安装 .NET 工作负载:
> 没有要显示的已安装工作负载。
> 
> Host:
>   Version:      8.0.4
>   Architecture: x64
>   Commit:       2d7eea2529
> 
> .NET SDKs installed:
>   6.0.301 [C:\Program Files\dotnet\sdk]
>   6.0.321 [C:\Program Files\dotnet\sdk]
>   8.0.202 [C:\Program Files\dotnet\sdk]
>   8.0.204 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 7.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> Other architectures found:
>   x86   [C:\Program Files (x86)\dotnet]
>     registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
> 
> Environment variables:
>   Not set
> 
> global.json file:
>   Not found
> 
> Learn more:
>   https://aka.ms/dotnet/info
> 
> Download .NET:
>   https://aka.ms/dotnet/download
